Change
cavalcanticampos/eldorado-pokedex pull request #8
Opened 2021-09-01 12:15 UTC by josaphamorim07

changing the backend , to our local java backend.

2021-09-02 12:16 UTC, cavalcanticampos requested changes
Tá daora Josaph.

Pra finalizar adiciona um fluxo pela queryParams para a páginação.

Ex.:
A rota inicia sempre no /pokedex?page=1

ao apertar os botões de troca de página é alterado também na url para page=2, page=3 etc.
Caso você troque direto na url /pokedex?page=7 a página precisa recarregar direto na página 7 .

2021-09-04 22:25 UTC, josaphamorim07 commented
change the url of the pokedex component making pagination work by parameters and adding Eslint to the project

2021-09-04 22:27 UTC, josaphamorim07 commented
change the url of the pokedex component making pagination work by parameters and adding Eslint to the project

2021-09-06 12:19 UTC, cavalcanticampos commented
Ainda tem alguns erros, assim como vários logs. Retira eles.

[
![Screenshot from 2021-09-06 08-17-48](https://user-images.githubusercontent.com/64264987/132216405-e3f67a68-a725-4c41-b1a7-e0eef07a4775.png)
](url)

2021-09-06 12:19 UTC, cavalcanticampos requested changes
Não funcionou a paginação aqui.

2021-09-06 13:04 UTC, cavalcanticampos approved these changes

2021-09-06 13:04 UTC, merged